### ISSUE TITLE
Add a Homebrew formula

### ISSUE THREAD

**Issue by jessedc** [jeanetienne/Cookie#7]
I've just installed this manually because it's become such a handy tool - it would be great to be able to use [homebrew](brew.sh) to install it too.

**Comment by jeanetienne** [comment]
Wow, I thought I was the only one using this...

Indeed, it would be nice to have it installed via `homebrew`... It's been on my list for a while. I'll look into it and update this issue.

**Comment by jeanetienne** [comment]
So I had a look at `brew.sh` documentation, turns out they say:

> We frown on authors submitting their own work unless it is very popular.

And also they have some rather detailed list of what makes an [acceptable formulae](https://docs.brew.sh/Acceptable-Formulae). So I guess I'll have to do a bit of prep work before being ready for publication.

When I'm ready I will create the necessary ruby file and detail the steps, and you could publish it (assuming it's only a matter of pushing a file to their repo)?

**Comment by jeanetienne** [comment]
It only took me 5 months, but now you can:

- `brew tap jeanetienne/cookie`
- `brew install cookie`

Hurray!
🎉
